"""The site's committed data must match what the repo currently produces.

`ui/web/src/data/*.json` is committed because the front end is a static build and
cannot read the repo at run time. That is the trade, and this is what it costs: a
retrained model or a rerun arm changes the numbers in the repo while the site keeps
serving the old ones, with nothing failing.

So the files are generated by `scripts/build_site_data.py` and this fails when they
drift. Anyone editing them by hand will be told to stop.

The failure message names the command, because the person who trips this is most
likely a teammate who did nothing wrong: they reran an eval and the site simply has
not been regenerated yet.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "ui" / "web" / "src" / "data"

pytestmark = pytest.mark.skipif(
    not (ROOT / "scripts" / "build_site_data.py").exists(),
    reason="site data generator not present",
)


def test_committed_site_data_matches_the_repo():
    """Regenerate in memory and compare. Fails if the site would show stale numbers."""
    result = subprocess.run(
        [sys.executable, "-m", "scripts.build_site_data", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        "The site's data files no longer match the repo.\n"
        f"{result.stdout}{result.stderr}\n"
        "Regenerate with: python -m scripts.build_site_data"
    )


def test_the_game_list_carries_no_result():
    """The picker reads a file whose source keeps the score beside the fixture."""
    games = json.loads((DATA / "games.json").read_text(encoding="utf-8"))["games"]
    forbidden = {"home_pts", "away_pts", "winner", "actual_home_win", "score"}
    leaked = sorted(forbidden.intersection(games[0]))
    assert not leaked, f"outcome fields reached the browser: {leaked}"


def test_every_tool_on_the_site_carries_its_skill_file():
    """The Tools tab shows the file verbatim; an empty one would show nothing."""
    tools = json.loads((DATA / "system.json").read_text(encoding="utf-8"))["tools"]
    missing = [t["name"] for t in tools if not t.get("skill_raw", "").strip()]
    assert not missing, f"tools shown with no skill file: {missing}"


def test_site_accuracy_agrees_with_the_model_file():
    """The System and Compare tabs must not disagree, which they once did by a game."""
    site = json.loads((DATA / "system.json").read_text(encoding="utf-8"))
    model = json.loads(
        (ROOT / "models" / "win_probability.json").read_text(encoding="utf-8")
    )
    assert site["win_model"]["accuracy"] == model["metrics"]["test"]["accuracy"]
    assert (
        site["arms"]["season"]["arm_A"]["accuracy"]
        == model["metrics"]["test"]["accuracy"]
    ), (
        "The season replay and the model file disagree on accuracy. Last time this "
        "happened it was 4-decimal rounding flipping one game at the 0.5 boundary."
    )
