"""Regenerate the site's data files from the repository.

    python -m scripts.build_site_data          # write
    python -m scripts.build_site_data --check  # fail if the committed files are stale

Everything the site displays is derived here: the tool list and skill files, the
composed system prompt, the datasets with row counts, and the fitted model contract.

WHY THIS EXISTS. `ui/web/src/data/*.json` is committed, because the front end is a
static build and cannot read the repo at run time. Committed derived data goes
stale silently: someone retrains a model or reruns an arm, the numbers in the repo
move, and the site keeps showing the old ones with no test failing. So the files
are generated by this script and `tests/test_site_data.py` fails when what is
committed no longer matches what this would produce.

WHAT IS HAND-WRITTEN, AND WHY IT IS HERE. The prose blocks below -- the gate rules
and the note about the model's knowledge cutoff -- are editorial, not derived. They
live in this file rather than in the JSON so that the JSON has exactly one author
and can be regenerated without losing anything. Edit them here.

Numbers are never typed in. If a figure appears on the site it was computed from a
file in this repo, and rerunning this script is how it changes.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from agent.skills import load_skills  # noqa: E402
from agent.sources import get_source  # noqa: E402
from agent.teams import full_name  # noqa: E402
from agent.tools import build_tools  # noqa: E402

OUT_DIR = ROOT / "ui" / "web" / "src" / "data"
BLOB = "https://github.com/joshcannonai/nba-game-intelligence-agent/blob/main/"

# Which files each tool reads. Kept here rather than inferred, because a tool
# reaches its data through the source layer and the mapping is a documentation
# decision, not something the code states.
TOOL_FILES = {
    "retrieve_matchup_context": [
        "data/raw/nba_stats_1947_present/Team Summaries.csv",
        "data/raw/injury_data_2016_2025/injury_data.csv",
        "data/samples/game_logs_2026.csv",
    ],
    "retrieve_team_form": ["data/samples/game_logs_2026.csv"],
    "retrieve_player_splits": ["data/raw/nba_stats_1947_present/Player Per Game.csv"],
    "retrieve_schedule": ["data/samples/game_logs_2026.csv"],
    "retrieve_injuries": [
        "data/raw/injury_data_2016_2025/injury_data.csv",
        "data/raw/injury_pst_2025_2026/injury_data.csv",
    ],
    "predict_win_probability": ["models/win_probability.json"],
    "predict_stat_line": [
        "models/stat_line.json",
        "data/samples/player_features_2026.csv",
    ],
}
# Two injury files share a basename; say which is which.
NICE_NAME = {
    "data/raw/injury_data_2016_2025/injury_data.csv": "injury_data.csv (2016-2025)",
    "data/raw/injury_pst_2025_2026/injury_data.csv": "injury_data.csv (2025-26)",
}

DATASETS = [
    (
        "data/samples/game_logs_2026.csv",
        "Every 2025-26 game: date, teams, result",
        "Kirtan / Patrick",
    ),
    (
        "data/samples/odds_only.csv",
        "Vegas closing lines, rebuilt without score columns",
        "Kirtan",
    ),
    (
        "data/samples/player_features_2026.csv",
        "Per-player trailing form, outcome columns stripped",
        "Josh, from Patrick's export",
    ),
    (
        "data/exports/player_stats_engineered.csv",
        "Per-player box scores with rolling features",
        "Patrick",
    ),
    (
        "data/exports/team_game_stats_engineered.csv",
        "Per-team game stats with rolling features",
        "Patrick",
    ),
    (
        "data/raw/injury_data_2016_2025/injury_data.csv",
        "Injury transaction log, 2016-2025",
        "Kirtan",
    ),
    (
        "data/raw/injury_pst_2025_2026/injury_data.csv",
        "Injury log continued through 2025-26",
        "Josh",
    ),
    (
        "data/raw/nba_stats_1947_present/Team Summaries.csv",
        "Season team ratings, 1947-present",
        "Kirtan",
    ),
    (
        "data/raw/nba_stats_1947_present/Player Per Game.csv",
        "Season player averages, 1947-present",
        "Kirtan",
    ),
]

LLM = {
    "name": "gemma4",
    "params": "8B",
    "quant": "Q4_K_M",
    "runtime": "Ollama, local",
    "cutoff": "~January 2025",
    "api_key_required": False,
    "why_cutoff_matters": (
        "The agent is graded on the 2025-26 season. Gemma 4's training data ends "
        "before that season began, so it cannot have memorised any result it is "
        "asked to predict. That is why evaluation uses this local model rather "
        "than a frontier API model whose cutoff we cannot verify."
    ),
}

GATE_RULES = [
    {
        "title": "It only sees yesterday's news",
        "body": "Injuries come from a dated log. We replay it and stop at the cutoff, so the agent sees exactly what a person could have known that morning.",
    },
    {
        "title": "Last season's ratings, not this one's",
        "body": "Season stats are end-of-year totals. Using this season's would include games that have not happened yet, so we serve last season's and say so.",
    },
    {
        "title": "Missing stays missing",
        "body": "If something cannot be worked out, the answer is unknown, with a reason. A blank is never treated as a zero.",
    },
    {
        "title": "It cannot see the betting line",
        "body": "The Vegas line is what we grade ourselves against, so the agent has no tool for it and the odds file is rebuilt without the final score.",
    },
]


def row_count(path: Path) -> int | None:
    try:
        with path.open(encoding="utf-8") as f:
            return sum(1 for _ in f) - 1
    except OSError:
        return None


def build_system() -> dict:
    from agent.run import SYSTEM, SYSTEM_NO_MODEL
    from agent.skills import skills_block

    skills = load_skills()
    source = get_source("real")
    names = [t.name for t in build_tools(source, include_model=True)]

    tools = []
    for name in names:
        sk = skills.get(name)
        files = TOOL_FILES.get(name, [])
        tools.append(
            {
                "name": name,
                "use_when": sk.use_when if sk else "",
                "skill": sk.body if sk else "",
                "skill_raw": sk.path.read_text(encoding="utf-8").strip() if sk else "",
                "skill_path": f"skills/{sk.path.name}" if sk else "",
                "skill_url": BLOB + f"skills/{sk.path.name}" if sk else "",
                "sources": [NICE_NAME.get(f, f.split("/")[-1]) for f in files],
                "source_links": [
                    {
                        "label": NICE_NAME.get(f, f.split("/")[-1]),
                        "url": BLOB + f,
                        "path": f,
                    }
                    for f in files
                ],
                # A tool is live when something backs it. The two that were not are
                # both finished now, so this is computed rather than hand-maintained.
                "status": "live",
            }
        )

    wp = json.loads(
        (ROOT / "models" / "win_probability.json").read_text(encoding="utf-8")
    )
    base_c = SYSTEM
    block_c = skills_block(names)
    block_b = skills_block([n for n in names if n != "predict_win_probability"])

    return {
        "tools": tools,
        "llm": LLM,
        "win_model": {
            "kind": wp["model"],
            "features": len(wp["feature_names"]),
            "train_seasons": wp["train_seasons"],
            "test_season": wp["test_season"],
            "accuracy": wp["metrics"]["test"]["accuracy"],
            "n": wp["metrics"]["test"]["n"],
            "log_loss": wp["metrics"]["test"]["log_loss"],
            "brier": wp["metrics"]["test"]["brier"],
            "feature_names": wp["feature_names"],
            "coefficients": wp["coefficients"],
        },
        "gate_rules": GATE_RULES,
        "prompt": {
            "base": base_c.strip(),
            "skills_block": block_c.strip(),
            "base_chars": len(base_c),
            "skills_chars": len(block_c),
            "total_chars": len(base_c + block_c),
            "arm_b_total": len(SYSTEM_NO_MODEL + block_b),
            "composed_in": "agent/skills.py",
            "base_in": "agent/run.py",
        },
        "datasets": [
            {
                "path": path,
                "what": what,
                "who": who,
                "rows": row_count(ROOT / path),
                "kb": round((ROOT / path).stat().st_size / 1024),
                "url": BLOB + path,
            }
            for path, what, who in DATASETS
            if (ROOT / path).exists()
        ],
    }


def build_games() -> dict:
    """The picker's game list. Identity and date only; never a score.

    `game_logs_2026.csv` keeps `home_pts`, `away_pts` and `winner` in the same row
    as the fixture, so this asserts they did not come along for the ride.
    """
    rows = list(
        csv.DictReader(
            (ROOT / "data/samples/game_logs_2026.csv").open(encoding="utf-8")
        )
    )
    games = []
    for r in rows:
        d = date.fromisoformat(r["game_date"])
        games.append(
            {
                "id": r["game_id"],
                "d": r["game_date"],
                "a": r["away"],
                "h": r["home"],
                "asOf": (d - timedelta(days=1)).isoformat(),
            }
        )
    games.sort(key=lambda g: (g["d"], g["id"]))
    leaked = {"home_pts", "away_pts", "winner"} & set(games[0])
    if leaked:
        raise AssertionError(f"outcome columns reached the game list: {sorted(leaked)}")
    teams = sorted({g["a"] for g in games} | {g["h"] for g in games})
    return {"games": games, "names": {t: full_name(t) for t in teams}}


def main() -> None:
    ap = argparse.ArgumentParser(description="Regenerate the site's data files")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed files are out of date",
    )
    args = ap.parse_args()

    targets = {
        OUT_DIR / "system.json": (build_system(), 2),
        OUT_DIR / "games.json": (build_games(), None),
    }

    stale = []
    for path, (payload, indent) in targets.items():
        text = (
            json.dumps(payload, indent=indent)
            if indent
            else json.dumps(payload, separators=(",", ":"))
        )
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current.rstrip("\n") != text.rstrip("\n"):
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    if args.check:
        if stale:
            print("STALE, the site would show numbers the repo no longer produces:")
            for s in stale:
                print(f"  {s}")
            print("\nFix with: python -m scripts.build_site_data")
            raise SystemExit(1)
        print("site data is current")
        return

    d = targets[OUT_DIR / "system.json"][0]
    print(f"\n  {len(d['tools'])} tools, all live")
    print(f"  prompt {d['prompt']['total_chars']} chars")
    print(f"  fitted Model A {d['win_model']['accuracy']:.4f}")
    print(f"  {len(targets[OUT_DIR / 'games.json'][0]['games'])} games in the picker")
    print("\nRebuild the front end after this: cd ui/web && bun run build")


if __name__ == "__main__":
    main()
